export const CHANGE_CURRENT_MENU_KEY = "CHANGE_CURRENT_MENU_KEY";
export const DEVICE_LIST = "DEVICE_LIST";
export const SERVICE_LIST = "SERVICE_LIST";
export const SERVICE_ADD = "SERVICE_ADD";
export const SYSTEM_LIST = "SYSTEM_LIST";
export const COMPONENT_LIST = "COMPONENT_LIST";
